- hosts: webserver
  tasks:
    # sudo apt-get update
  - name: Update apt packages
    sudo: yes
    apt:
      update_cache: yes
    tags:
      - system

  - name: Add Docker GPG key
    sudo: yes
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    sudo: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

  - name: Install list of packages
    sudo: yes
    apt:
      name: ['apt-transport-https','ca-certificates','curl','software-properties-common','docker-ce']
      state: present
      update_cache: yes
