---

- name: Provision a Jenkins CI server
  hosts: webserver
  become: yes
  become_user: root
  remote_user: root
  vars:
    - update_apt_cache: yes

  roles:
#    - base
#    - certbot
    - jenkins
#    - nginx
