---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Add Felix Krull's New Python Versions PPA to the apt sources list
  apt_repository: repo='ppa:fkrull/deadsnakes'
                  update_cache={{ update_apt_cache }}
                  state=present

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - awscli
    - build-essential
    - apt-transport-https
    - ca-certificates
    - acl
    - ntp
    - htop
    - git
    - libpq-dev
    - python3.6
    - "{{ base_python_package }}-dev"
    - "{{ base_python_package }}-pip"
    - python-pycurl
    - supervisor
    - unzip
  tags: packages
